Homework 5
lebedeeva/JS-Summer-Cucumber-2022 pull request #1
Opened 2022-08-31 05:01 UTC by lebedeeva

2022-09-02 18:41 UTC, lebedeeva commented
@ahsansiddiki

2022-09-02 21:25 UTC, ahsansiddiki commented on Pages/Hotels/Homepage.js
> +    checkInDay = 1
This is hard coded. It should be dynamic so that the test works everyday without modification.

2022-09-02 21:25 UTC, ahsansiddiki commented on Pages/Hotels/Homepage.js
> +    checkOutDay = 6
Same here.

2022-09-02 21:26 UTC, ahsansiddiki commented on step-definitions/Hotels/homework.js
> +Then(/^I go to the needed month$/, async function(){
This is an action, all action SD should be labelled as **When**.

2022-09-02 21:26 UTC, ahsansiddiki commented on step-definitions/Hotels/homework.js
> +Then(/^I type Man in destination$/, async function(){
Action step.

2022-09-02 21:27 UTC, ahsansiddiki commented on step-definitions/Hotels/homework.js
> +Then(/^I select Manila from auto-suggestion$/, async function(){
Action step.

2022-09-02 21:28 UTC, ahsansiddiki requested changes
Pls modify all action steps as When.

2022-09-04 10:57 UTC, ahsansiddiki requested changes
1786 files in this PR, bcz its included allure-report files. Pls use `git rm -r allure-report` to remove the folder.

2022-09-04 19:36 UTC, lebedeeva commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
code
	{mso-style-priority:99;
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Okay, done. Sent from Mail for Windows From: Ahsan SiddikiSent: Sunday, September 4, 2022 6:58 AMTo: lebedeeva/JS-Summer-Cucumber-2022Cc: lebedeeva; AuthorSubject: Re: [lebedeeva/JS-Summer-Cucumber-2022] Homework 5 (PR ***@***.*** requested changes on this pull request.1786 files in this PR, bcz its included allure-report files. Pls use git rm -r allure-report to remove the folder.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2022-09-04 20:32 UTC, ahsansiddiki commented
@lebedeeva Stilll all the files here in PR
![FABAF665-B95A-47BC-AB70-3737AE8C4B84](https://user-images.githubusercontent.com/30092854/188332318-214acaf7-8d19-4597-a898-8d6dd9508ee8.png)

2022-09-04 23:24 UTC, closed without merging

2022-09-04 23:29 UTC, lebedeeva commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Hi, I tried everything and cannot find a way to delete it. I deleted the whole branch now but it only complicated it more for me…can you please help?  Sent from Mail for Windows From: Ahsan SiddikiSent: Sunday, September 4, 2022 4:33 PMTo: lebedeeva/JS-Summer-Cucumber-2022Cc: lebedeeva; MentionSubject: Re: [lebedeeva/JS-Summer-Cucumber-2022] Homework 5 (PR ***@***.*** Stilll all the files here in PR—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 